//
// Created by samuel on 2025/02/12.
//

#ifndef CARCOMPUTER_SPECIAL_CHARS_H
#define CARCOMPUTER_SPECIAL_CHARS_H

#define SPECIAL_CHAR_DEGREES (248)
#define SPECIAL_CHAR_LOCATION (181)
#define SPECIAL_CHAR_BLUETOOTH (182)
#define SPECIAL_CHAR_SD_CARD (183)
#define SPECIAL_CHAR_CIRCLE_CLOSED (184)
#define SPECIAL_CHAR_CIRCLE_OPEN (185)
#define SPECIAL_CHAR_TICK_MARK (186)
#define SPECIAL_CHAR_CROSS_MARK (187)
#define SPECIAL_CHAR_POWER2 (253)
#define SPECIAL_CHAR_ARROW_LEFT (188)
#define SPECIAL_CHAR_ARROW_RIGHT (189)
#define SPECIAL_CHAR_LOCK (192)

#endif //CARCOMPUTER_SPECIAL_CHARS_H